services:
  node-app:
    build: ./node_demo
    ports:
      - "3000:3000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DB_PATH=/app/db.sqlite3

  django-app:
    build: ./django_demo
    ports:
      - "5000:5000"
    volumes:
      - ./db.sqlite3:/app/myproject/db.sqlite3
    environment:
      - DB_PATH=/app/myproject/db.sqlite3


#  springboot-app:      TODO
#    build: ./springboot_demo
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./db.sqlite3:/app/db.sqlite3
#    environment:
#      - DB_PATH=/app/db.sqlite3