
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=never 
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect #Hacemos que springboot use este dialecto nuevo
spring.jpa.hibernate.ddl-auto=update    #Queremos podemos realizar cambios en la database
